### ISSUE TITLE
When in watch mode, new launcher created on every change

### ISSUE THREAD

**Issue by mistadikay** [start-runner/karma#1]
I'm not sure if it's the actual bug, or maybe I'm doing something wrong.

**Steps to reproduce:**
1. `git clone https://github.com/mistadikay/react-workshop.git`
2. `npm i`
3. `npm start tdd`
4. change something in `test/src/components/app/index.js` so tests would rerun

**Expected result:**
Tests would rerun in the same launcher instance

**Actual result:**
There is a new launcher instance created on every change
<img width="156" alt="screen shot 2016-02-22 at 18 58 09" src="https://cloud.githubusercontent.com/assets/742056/13217648/9c785534-d996-11e5-87c6-d98a48864183.png">

**Comment by mistadikay** [comment]
It appears that because karma has its own watcher, it's probably conflicting with `start-watch`, so the solution to this would be to not use `watch` with `karma` and use built-in watcher instead.

**Comment by deepsweet** [comment]
https://github.com/start-runner/watch/commit/5ac4ff2f01f5135c489997fdf890a1925b270799
